path: C:\Users\adity\Downloads\archive
train: train/images
val: train/images

# Classes
names:
  0: green_light
  1: red_light
  2: speed_limit_10
  3: speed_limit_100
  4: speed_limit_110
  5: speed_limit_120
  6: speed_limit_20
  7: speed_limit_30
  8: speed_limit_40
  9: speed_limit_50
  10: speed_limit_60
  11: speed_limit_70
  12: speed_limit_80
  13: speed_limit_90
  14: stop
